# Generated by Django 6.0.1 on 2026-01-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('type', models.CharField(choices=[('channel', 'Channel'), ('group', 'Group'), ('supergroup', 'Supergroup')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('members_count', models.IntegerField(blank=True, null=True)),
                ('last_checked_message_id', models.BigIntegerField(blank=True, null=True)),
                ('is_safe', models.BooleanField(default=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('discovered_by', models.CharField(choices=[('admin_query', 'Admin Query'), ('forward', 'Forwarded Post'), ('mention', 'Mention'), ('link', 'Invite Link')], default='admin_query', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
