# Generated by Django 6.0.1 on 2026-01-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_telegramchat_delete_channel_delete_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
