# Generated by Django 6.0.1 on 2026-01-21 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_telegramchat_first_name_telegramchat_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='last_checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
