# Generated by Django 6.0.1 on 2026-01-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_telegramchat_last_checked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='type',
            field=models.CharField(choices=[('channel', 'Channel'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('user', 'User')], max_length=20),
        ),
    ]
