# Generated by Django 6.0.1 on 2026-01-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_telegramchat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='listening',
            field=models.BooleanField(default=False),
        ),
    ]
