# Generated by Django 6.0.1 on 2026-01-21 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_telegramchat_listening'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='telegramchat',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='telegramchat',
            name='is_safe',
        ),
        migrations.RemoveField(
            model_name='telegramchat',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='telegramchat',
            name='risk_score',
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='risk',
            field=models.CharField(choices=[('safe', 'Safe'), ('risky', 'Risky'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='members_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='type',
            field=models.CharField(choices=[('channel', 'Channel'), ('group', 'Group'), ('supergroup', 'Supergroup')], max_length=20),
        ),
        migrations.CreateModel(
            name='WarningMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.telegramchat')),
            ],
        ),
    ]
