# Generated by Django 6.0.1 on 2026-01-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_tguser_remove_telegramchat_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='tg_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
