# Generated by Django 6.0.1 on 2026-01-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_telegramchat_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='warningmessage',
            name='user_tg_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
